// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';

const SUPABASE_URL = "https://vsxbmdghnqyhcyldjdoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzeGJtZGdobnF5aGN5bGRqZG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTcwNjgsImV4cCI6MjA2MDM3MzA2OH0.4191FRa6bXC_SOtkYwt2DpBKzr80GUsNy4ORMAvPlMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Erweiterte Optionen für mobile Geräte
const supabaseOptions = {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: !Capacitor.isNativePlatform(), // Nur im Web aktivieren
    flowType: 'pkce' as const, // Sichere PKCE Flow für mobile Geräte verwenden
  },
  global: {
    headers: {
      'X-Client-Info': `fi-investments-app/${Capacitor.getPlatform()}`,
    },
  },
  realtime: {
    // Bessere Realtime-Konfiguration für mobile Verbindungen
    heartbeatIntervalMs: 30000,
    reconnectAfterMs: (tries: number) => Math.min(tries * 1000, 10000),
  },
};

console.log('Initializing Supabase client with platform:', Capacitor.getPlatform());
console.log('Supabase URL:', SUPABASE_URL);

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  supabaseOptions
);